name: bmc-commissioner

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bmc-commissioner-app
    ports:
      - '8080:80'
    depends_on:
      - db

  db:
    build:
      context: 'pb'
      dockerfile: Dockerfile
    image: bmc-commissioner-db
    ports:
      - '8090:8090'
    volumes:
      - db-data:/pb/data

volumes:
  db-data:
