# name: bmc-commissioner

services:
  app:
    image: bmc-commissioner-app:latest
    ports:
      - '8083:80'
    depends_on:
      - db

  db:
    image: bmc-commissioner-db:latest
    volumes:
      - db-data:/pb/data
    ports:
      - '8084:8090'

volumes:
  db-data:
