name: Build and deploy app with docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Export Docker images as tarballs
        run: npm run docker:export

      - name: Change permissions of the tarball
        run: chmod 644 ./build/bmc-commissioner-app.tar && chmod 644 ./build/bmc-commissioner-db.tar

      - name: Upload tarball files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bmc-commissioner-artifacts
          path: |
            ./build/*.tar
            ./build/*.yml
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact files
        uses: actions/download-artifact@v3
        with:
          name: bmc-commissioner-artifacts
          path: ./build

      - name: Transfer tarballs and docker compose files to the server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: './build/'
          target: '$HOME/bmc-commissioner'

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd $HOME/bmc-commissioner
            docker-compose -f docker-compose.yml down
            docker load -i fbmc-commissioner-app.tar
            docker load -i fbmc-commissioner-db.tar
            docker-compose -p bmc-commissioner -f docker-compose.yml up --build -d
