name: Build and deploy app with docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Export Docker images as tarballs
        run: npm run docker:export

      - name: Change permissions of the tarball
        run: chmod 644 ./build/bmc-commissioner-app.tar && chmod 644 ./build/bmc-commissioner-db.tar

      - name: Upload app image file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bmc-commissioner-app.tar
          path: ./build/bmc-commissioner-app.tar
          if-no-files-found: error

      - name: Upload db imagefiles as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bmc-commissioner-db.tar
          path: ./build/bmc-commissioner-db.tar
          if-no-files-found: error

      - name: Upload docker compose deploy file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose.yml
          path: ./build/docker-compose.yml
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download app image artifact
        uses: actions/download-artifact@v4
        with:
          name: bmc-commissioner-app.tar
          path: ./build

      - name: Download db image artifact
        uses: actions/download-artifact@v4
        with:
          name: bmc-commissioner-db.tar
          path: ./build

      - name: Download docker compose deployment file
        uses: actions/download-artifact@v4
        with:
          name: docker-compose.yml
          path: ./build

      - name: Transfer tarballs and docker compose files to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: 'build/*.tar,build/*.yml'
          target: '$HOME/bmc-commissioner'
          strip_components: 1

      # - name: SSH into server and deploy
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     script: |
      #       cd $HOME/bmc-commissioner
      #       docker-compose -f docker-compose.yml down
      #       docker load -i bmc-commissioner-app.tar
      #       docker load -i bmc-commissioner-db.tar
      #       docker-compose -p bmc-commissioner -f docker-compose.yml up --build -d
